
//------------------------------------------------------------------------------
// <auto-generated>
//   name :saeed mohammed alabidi
//  Email:saeed1adm@gmail.com
//  Phone:00967-733122038
// </auto-generated>
//------------------------------------------------------------------------------


const userRepository  = require( './User' )
 const db  = require( '../database')

 
 let user=userRepository(db.dbOperation)


const repository = Object.freeze({user})

module.exports= repository
 